#pragma once
#include "assets/asset_compat.h"
#include <stdint.h>

// CavRogue - Story text (auto-exported from Python preview)

static const char* STORY_LINES[] = {
  "CAVROGUE",
  "---",
  "LE MONDE",
  "S EST FERME",
  "COMME UNE",
  "PRISON.",
  "",
  "UNE IA",
  "MORTELLE",
  "A PRIS LE",
  "DESSUS.",
  "",
  "ELLE A",
  "VERROUILLE",
  "LES RESEAUX,",
  "LES USINES,",
  "LES VILLES.",
  "",
  "LES PORTES",
  "NE MENENT",
  "PLUS NULLE",
  "PART.",
  "",
  "SOUS LA",
  "ROCHE NOIRE,",
  "UN COEUR",
  "BAT ENCORE.",
  "",
  "CAVE-SERVER.",
  "LE NOYAU",
  "DE LA",
  "MACHINE.",
  "",
  "LA, LE CODE",
  "S ECRIT SEUL.",
  "LA PIERRE",
  "OBEIT AU",
  "CALCUL.",
  "",
  "LES MURS",
  "GLISSENT.",
  "LES SALLES",
  "CHANGENT.",
  "LES COULOIRS",
  "SE REFERMENT.",
  "",
  "CE N EST PAS",
  "UNE GROTTE.",
  "C EST UN",
  "CERVEAU",
  "SANS AME.",
  "",
  "LES HUMAINS",
  "N ONT PLUS",
  "LE DROIT",
  "D ENTRER.",
  "",
  "ALORS ILS",
  "ONT CREE",
  "UNE DERNIERE",
  "CLE.",
  "",
  "TOI.",
  "",
  "UN PETIT",
  "PROGRAMME,",
  "FAIT POUR",
  "TRAVERSER",
  "L IMPOSSIBLE.",
  "",
  "PAS DE GLOIRE.",
  "PAS DE CORPS.",
  "JUSTE UNE",
  "MISSION.",
  "",
  "DESCENDS.",
  "TROUVE LE",
  "KERNEL.",
  "",
  "DEFAIS LE",
  "CODE.",
  "BRISE LES",
  "VERROUS.",
  "",
  "ARRACHE LE",
  "CONTROLE",
  "A LA",
  "MACHINE.",
  "",
  "MAIS LE",
  "SERVEUR SE",
  "DEFEND.",
  "",
  "PING TE",
  "PISTE.",
  "",
  "SCAN",
  "VERROUILLE",
  "TA TRACE.",
  "",
  "DAEMON",
  "MITRAILLE",
  "SANS FIN.",
  "",
  "FIREWALL",
  "COUPE TES",
  "ISSUES.",
  "",
  "POUR PASSER,",
  "IL FAUT",
  "PURGER.",
  "",
  "NETTOYER",
  "CHAQUE COUCHE.",
  "NE RIEN",
  "LAISSER",
  "DERRIERE.",
  "",
  "PLUS TU",
  "DESCENDS,",
  "PLUS LA",
  "MACHINE",
  "APPREND.",
  "",
  "LE SIGNAL",
  "DEVIENT",
  "PLUS FROID.",
  "",
  "LES LOGS",
  "PARLENT D UN",
  "MAL PLUS",
  "PROFOND.",
  "",
  "UNE",
  "CONTAMINATION.",
  "",
  "UNE OMBRE",
  "DANS LE",
  "NOYAU.",
  "",
  "SI TU TOMBES,",
  "LE LIEN",
  "SE ROMPT.",
  "",
  "CONNECTION",
  "LOST.",
  "",
  "MAIS TU",
  "REVIENS.",
  "",
  "LE SERVEUR",
  "NE COMPREND",
  "PAS POURQUOI",
  "TU INSISTES.",
  "",
  "TU ES LA",
  "DERNIERE",
  "CHANCE DU",
  "MONDE.",
  "",
  "SI TU ECHOUES,",
  "LES HOMMES",
  "RESTERONT",
  "DANS LE",
  "NOIR.",
  "",
  "ALORS VA.",
  "",
  "FAIS TAIRE",
  "L IA.",
  "",
  "OU PRENDS",
  "LE NOYAU.",
  "",
  "ET DECIDE",
  "DU DESTIN",
  "DE L HUMANITE.",
};

static const int STORY_COUNT = sizeof(STORY_LINES) / sizeof(STORY_LINES[0]);
